### ISSUE TITLE
Optimise TransactionFee and Query fee for call methods

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hethers.js#104]
Currently we have hardcoded:
- 3 hbar for the query fee
- 1 hbar for transaction fee (for the payment)

1) We must use `getCost` method from the SDK to get the actual cost 
2) We must lower the `hbar` fee for the crypto transfer (1 hbar is too high)

**Comment by natanasow** [comment]
Only `transactionFee` is changed.
