### ISSUE TITLE
Review `publish` script

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [hashgraph/hethers.js#174]

**Comment by Ivo-Yankov** [comment]
I analyzed the script and here is a short description of what it does:

1. Reads config data from a file
2. Loops through all directories in ./packages/
3. Compares the version of every package.json and the corresponding package in NPM. If the version is the same the package is skipped.
4. Gets the last git commit hash for the directory: `git log -n 1 -- packages/abi`
5. Writes that hash in package.json in a property `gitHead`. Publishes it to NPM. Then deletes `gitHead` from package.json

This means that the packages are published with the gitHead property. We can check that if we install ethers and open it's package.json

6.  Takes the hash(sha384) of `packages/ethers/dist/ethers.umd.min.js` and uses it to create a release via the GitHub API: `POST api.github.com/repos/ethers-io/ethers.js/releases`

7. Uploads the minified js files from `packages/ethers/dist/` to AWS.S3 in several different buckets and then invalidates the cached files in AWS.CloudFront.
