### ISSUE TITLE
Signer (wallet) initialization does not accept private keys that don't start with 0x - documentation says otherwise

### ISSUE THREAD

**Issue by ed-marquez** [hashgraph/hethers.js#232]
[This hethers doc page](https://docs.hedera.com/hethers/application-programming-interface/signers#wallet) reads:
    _Note: ECDSA privateKeys which do not start with 0x are also accepted._

Hethers at the moment is only accepting private keys that start with 0x during Wallet initialization. 

The example code you have in documentation works (because keys start with 0x). 

The same code with a few changes does not work and results in the following error: 
```
const provider = hethers.providers.getDefaultProvider("testnet");
	const eoaAccount = {
		account: "0.0.34134094",
		privateKey:
			"3030020100300706052b8104000a04220420c2807e0316db9e37cbb8d22e0139dfdf3a0d367acd661a1c417583dedf9f7c3f",
	};
	const walletEoaAccount = new hethers.Wallet(eoaAccount, provider);
```
ERROR:

```
Error: invalid hexlify value (argument="value", value={"account":"0.0.34134094","privateKey":"3030020100300706052b8104000a04220420c2807e0316db9e37cbb8d22e0139dfdf3a0d367acd661a1c417583dedf9f7c3f"}, code=INVALID_ARGUMENT, version=bytes/5.5.0)
    at Logger.makeError (C:\Work\smart-contracts\hethers\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (C:\Work\smart-contracts\hethers\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at Logger.throwArgumentError (C:\Work\smart-contracts\hethers\node_modules\@ethersproject\logger\lib\index.js:245:21)
    at hexlify (C:\Work\smart-contracts\hethers\node_modules\@hethers\wallet\node_modules\@ethersproject\bytes\lib\index.js:200:19)
    at new SigningKey (C:\Work\smart-contracts\hethers\node_modules\@hethers\wallet\node_modules\@ethersproject\signing-key\lib\index.js:20:82)
    at new Wallet (C:\Work\smart-contracts\hethers\node_modules\@hethers\wallet\lib\index.js:148:36)
```

**Comment by arrusev** [comment]
The problem here is with the private key, full-length keys are not currently supported.

You should convert it into a shorter key using the SDK:
PrivateKey.fromString(<your private key>).toStringRaw()

**Comment by ed-marquez** [comment]
Thanks for clarifying. Yes, I eventually arrived at that conclusion after noticing that the keys in the doc examples were shorter than “regular” hedera keys.

So are only short ECDSA keys supported at the moment by hethers? Or are short ED25xx keys also supported now? 

The .toStringRaw() method works on both types of keys, but I believe I may have been running into issues earlier due to the key being ED25xx rather than ECDSA. Will test again today, but confirmation will help.

**Comment by arrusev** [comment]
Only ECDSA keys are supported at the moment.  

We are currently working on adding ED25519 keys as well but it is still in early stage.
