### ISSUE TITLE
Hethersjs produces invalid URLs when subscribing to events

### ISSUE THREAD

**Issue by supermonkeybrainz** [hashgraph/hethers.js#235]
All, trying to use hethers to get contract event data.  However, the library seems to be creating invalid URLs to the mirror nodes.  Ex.

```
https://testnet.mirrornode.hedera.com/api/v1/contracts/0x0000000_ETHADDRESS_/results/logs?limit=101&topic0=0x_SOMETOPIC_&timestamp=lte%3A_TIMESTAMP_&timestamp=gte%3A_TIMESTAMP_
```

^^ Notice how the contract ID is ETH address.

```
  const contract = new hethers.Contract('0.0.123456', myAbi, provider)
  contract.on('SomeEvent', (...other) => {})
```

All relevant details, including the code path and precisely where in the code the problem is may be found on the Hedera Discord here:

https://discord.com/channels/373889138199494658/909532351388864542/969016299168608296

**Comment by supermonkeybrainz** [comment]
Any word on this?

**Comment by supermonkeybrainz** [comment]
Any word on this?

**Comment by supermonkeybrainz** [comment]
All, this is a critical bug.  Will there be a fix?

**Comment by Kalina-Todorova** [comment]
This should be fixed now.
