### ISSUE TITLE
provider.getBalance gives error for contract address parameter

### ISSUE THREAD

**Issue by rahuljaguste** [hashgraph/hethers.js#247]
**Description**
Ideally provider.getBalance function should work for both account addresses and contract addresses. At present it only supports account addresses and not contract addresses.
hethers.getDefaultProvider().getBalance errors out on passing contract address. 

**Error**
    Error: bad result from backend (method="AccountBalanceQuery", params={"address":"0x00000000000000000000000000000000021456fa"}, error={"name":"StatusError","status":{"_code":15},"transactionId":{"accountId":{"shard":{"low":0,"high":0,"unsigned":false},"realm":{"low":0,"high":0,"unsigned":false},"num":{"low":0,"high":0,"unsigned":false},"aliasKey":null,"_checksum":null},"validStart":{"seconds":{"low":1653292466,"high":0,"unsigned":false},"nanos":{"low":770677894,"high":0,"unsigned":false}},"scheduled":false,"nonce":null}}, code=SERVER_ERROR, version=providers/1.1.1)

**Reproduction code**
await hethers.getDefaultProvider().getBalance("0x00000000000000000000000000000000021456fa"); 

**Bug Location**
@hethers/providers/src.ts/base-provider.ts
function name - getBalance
` const balance = await new AccountBalanceQuery().setAccountId(AccountId.fromString(account)).execute(this.hederaClient);`

**Fix**
Need to differentiate between account address and contract address and set the balance variable as below
` const balance = await new AccountBalanceQuery().setContractId(ContractId.fromString(account)).execute(this.hederaClient);`

**Search Terms**
getBalance
contract address
contract balance

**Comment by Kalina-Todorova** [comment]
Fixed by https://github.com/hashgraph/hethers.js/pull/248
