### ISSUE TITLE
Can't override axios headers for authorization

### ISSUE THREAD

**Issue by supermonkeybrainz** [hashgraph/hethers.js#251]
**Describe the bug**
Hethers uses axios under the hood to do it's polling.  This makes it difficult (impossible?) to integrate with mirror providers that require custom authorization headers.

Please allow overriding of axios options for requests, specifically for headers.

**Reproduction steps**
Any contract event listening.

**Environment:**
Everywhere

**Search Terms**
axios

**Comment by themelnick** [comment]
this is a key capability need to allow commercial mirrors

**Comment by supermonkeybrainz** [comment]
All, any word on this?  Really important for commercial mirror integration, which is critical for any serious application.

**Comment by supermonkeybrainz** [comment]
Is there a status update on this issue?

**Comment by Kalina-Todorova** [comment]
@supermonkeybrainz we are picking this up and will release with the fix

**Comment by supermonkeybrainz** [comment]
Thanks! :D
