### ISSUE TITLE
Fix default cost of `ContractCallQuery`

### ISSUE THREAD

**Issue by Kalina-Todorova** [hashgraph/hethers.js#273]
**Describe the bug**
- ContractCallLocal is $0.001
- ContractCall e $0.05

In the `packages/abstract-signer/src.ts/index.ts` the DEFAULT_HEDERA_CALL_TX_FEE is set to 143083413 which is around 14 HBARs. 

Lets aim to have it as close to the actual cost as possible.

**Environment:**
Everywhere 

**Search Terms**
call cost, hbar

**Comment by mohsin-hedera** [comment]
From the user: 
![image](https://user-images.githubusercontent.com/92186249/186906686-805e9f19-9e07-4e52-b55e-bc3e130aa273.png)
