### ISSUE TITLE
Any documentation on which wallet (ie chrome extension) should we use with hedera. 

### ISSUE THREAD

**Issue by imsk17** [hashgraph/hethers.js#280]
As far as i know, hashpack is not supported

**Comment by Kalina-Todorova** [comment]
Hi @imsk17, you can take a look here: https://hedera.com/ecosystem/wallets-custody 
Hashpack is supported, you can check out some of their guides here: https://www.hashpack.app/support

**Comment by imsk17** [comment]
I did read their documentation and could not find any documentation on how to use it as an ethers signer.

**Comment by Kalina-Todorova** [comment]
Maybe this example from the json-rpc-relay might be useful to you: https://github.com/hashgraph/hedera-json-rpc-relay/tree/main/dapp-example / for additional info: https://swirldslabs.com/hashio/

**Comment by Kalina-Todorova** [comment]
Hope above info was helpful. In case you have more questions feel free to reach out in Disocrd: https://hedera.com/discord
